### ISSUE TITLE
If user submits --filter-types as lowercase, just capitalize it or don't check it against REGEX

### ISSUE THREAD

**Issue by UnKn0wN-Binary** [rileydakota/cfn-sweeper#28]
C:\Users\Root\Documents\GitHub\cfn-sweeper>cfn_sweeper --region ca-central-1 --filter-types AWS::EC2::instance
'AWS::EC2::instance'
Sorry - AWS::EC2::instance isnt supported just yet!
{}

C:\Users\Root\Documents\GitHub\cfn-sweeper>cfn_sweeper --region ca-central-1 --filter-types AWS::EC2::Instance

**Comment by rileydakota** [comment]
Closing - we decided to provide functionality to show supported resource types instead in #34 - this was both easier to implement, and given that CloudFormation itself is Case Sensitive, probably less confusing for the user
